version: "3.7"

services:
  nginx:
    image: nginx:1.19.5

    ports:
      - 80:80

    networks:
      - gis_4_2_network

    volumes:
      - /home/ljk8190/nginx.conf:/etc/nginx/nginx.conf
      - gis_4_2_static:/data/static
      - gis_4_2_media:/data/media

  django:
    image: gis_4_2_django:1.0.3

    networks:
      - gis_4_2_network

    volumes:
      - gis_4_2_static:/home/gis4_2/staticfiles/
      - gis_4_2_media:/home/gis4_2/media/

  mariadb:
    image: mariadb:10.5

    networks:
      - gis_4_2_network

    volumes:
      - gis_4_2_mariadb:/var/lib/mysql

    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234


networks:
  gis_4_2_network:

volumes:
  gis_4_2_static:
  gis_4_2_media:
  gis_4_2_mariadb: